# Конфигурация для assistant-telegram
server:
  port: ${server.telegram.port:8082}

spring:
  config:
    import: file:../application.yml

core:
  service:
    url: http://localhost:${server.core.port:8080}/api