# Конфигурация для assistant-telegram
server:
  port: ${server.telegram.port:8082}

spring:
  config:
    import: file:../application.yml

# URL ядра (assistant-core) для обращения из Telegram бота
core:
  service:
    url: http://localhost:${server.core.port:8080}/api

# URL веб-сервиса (assistant-web) для получения данных dashboard
web:
  service:
    url: http://localhost:${server.web.port:8082}

# Telegram Bot (переменные среды перекрывают значения из корневого application.yml)
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:${telegram.bot.token}}
    username: ${TELEGRAM_BOT_USERNAME:${telegram.bot.username}}