# Конфигурация для assistant-web
server:
  port: ${server.web.port:8081}

spring:
  # Не импортируем корневой файл, чтобы избежать дублирования URL ядра в веб-модуле
  config:
    import: ''

# URL ядра (assistant-core) для проксирования запросов из веб-интерфейса
core:
  service:
    url: http://localhost:${server.core.port:8080}

# URL модуля обновления базы данных (assistant-base_update) для API нарядов
base-update:
  service:
    url: http://localhost:${server.base-update.port:8084}