# Конфигурация для assistant-web
server:
  port: ${server.web.port:8081}

spring:
  config:
    import: file:../application.yml

core:
  service:
    url: http://localhost:${server.core.port:8080}/api